openapi: 3.0.0
info:
  title: StreamingCommunity API
  version: 1.0.0
  description: API for managing video downloads from various streaming websites.
servers:
  - url: /api/v1
paths:
  /search:
    get:
      summary: Search for videos
      operationId: searchVideos
      parameters:
        - in: query
          name: query
          schema:
            type: string
          required: true
          description: The search query (movie, TV show, or anime title).
        - in: query
          name: type
          schema:
            type: string
            enum: [movie, tv_show, anime]
          description: Optional filter for video type.
      responses:
        '200':
          description: A list of matching videos.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VideoSearchResult'
        '400':
          description: Invalid search query or parameters.
        '500':
          description: Internal server error.
  /download:
    post:
      summary: Initiate video download
      operationId: initiateDownload
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - videoId
              properties:
                videoId:
                  type: string
                  description: The ID of the video to download.
      responses:
        '200':
          description: Download initiated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DownloadStatus'
        '400':
          description: Invalid video ID or download request.
        '500':
          description: Internal server error.
  /download/{downloadId}/status:
    get:
      summary: Get download status
      operationId: getDownloadStatus
      parameters:
        - in: path
          name: downloadId
          schema:
            type: string
          required: true
          description: The ID of the download to retrieve status for.
      responses:
        '200':
          description: Current download status.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DownloadStatus'
        '404':
          description: Download not found.
        '500':
          description: Internal server error.
  /websites:
    get:
      summary: Get list of supported websites
      operationId: getSupportedWebsites
      responses:
        '200':
          description: A list of supported websites.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Website'
        '500':
          description: Internal server error.
components:
  schemas:
    VideoSearchResult:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the video.
        title:
          type: string
          description: Title of the video.
        websiteName:
          type: string
          description: Name of the website the video is from.
        thumbnailUrl:
          type: string
          format: url
          description: URL to a thumbnail image of the video.
    DownloadStatus:
      type: object
      properties:
        downloadId:
          type: string
          description: Unique identifier for the download operation.
        videoId:
          type: string
          description: The ID of the video being downloaded.
        status:
          type: string
          enum: [pending, downloading, completed, failed, cancelled]
          description: Current status of the download.
        progress:
          type: number
          format: float
          description: Download progress as a percentage (0-100).
        eta:
          type: string
          description: Estimated time remaining for download (e.g., "5m 30s").
        errorMessage:
          type: string
          description: Error message if download failed.
    Website:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the website.
        name:
          type: string
          description: Name of the website.
        baseUrl:
          type: string
          format: url
          description: Base URL of the website.
        supportedProtocols:
          type: array
          items:
            type: string
          description: List of supported download protocols (e.g., HLS, DASH, MP4, Torrent).
        supportsDrm:
          type: boolean
          description: Indicates if the website supports DRM protected content.
